### ISSUE TITLE
FTP Setting not loading in Just Ride events

### ISSUE THREAD

**Issue by derekkvedar** [philosowaffle/peloton-to-garmin#267]
**Describe the bug**
FTP Setting - not a statistic that loads in Just Ride events. This results in lack of TSS and IF for these workouts, which skews Garmin metrics. FTP will load for any other event (Power Zone ride, Climb Ride, Warmup Ride, etc), so from what I can tell, just the Just Ride events have this bug. v2.0.6

**Pictures**
![image](https://user-images.githubusercontent.com/84642403/180663762-20d36546-ae0a-4be0-b078-ee160b73ac75.png)
![image](https://user-images.githubusercontent.com/84642403/180663809-40e88249-d741-401a-b077-301c12ffc852.png)

**To Reproduce**
1. Execute any type of ride with an instructor (PZ, Warmup, etc).
2. Execute Just Ride.
3. Convert P2G.
4. Load into Garmin Connect.
5. Note lack of TSS and IF for Just Ride, but presence of TSS and IF (due to FTP Setting data point) for instructor rides.

**Expected behavior**
What should happen is a Just Ride gives a TSS and IF for each ride, in order to accurately assess fatigue.

**Logs**
```
Paste Log output here
```

**Installation (please complete the following information):**
 - OS: Windows
 - Method: exe
 - Version: 2.0.6

**Additional context**

**Comment by philosowaffle** [comment]
fixed in latest
scheduled for `v3` release.

**Comment by derekkvedar** [comment]
love that. when is v3 projected for release?

**Comment by philosowaffle** [comment]
Hopefully in the next week or so.  The remaining work for V3 is being tracked here:
https://github.com/philosowaffle/peloton-to-garmin/issues?q=is%3Aissue+is%3Aopen+milestone%3Av3

In the meantime, you can download the release candidate and give it a spin. Scroll to the bottom of the page and look for Artifacts to download the latest windows exe: 
https://github.com/philosowaffle/peloton-to-garmin/actions/runs/2766646163

Since you're coming from 2.0.6, you might want to take a look at the changelog for 2.1 and 2.2 to get a feel for what's new.  Note that the changelog does not include any of the updates/fixes for V3 yet.
https://github.com/philosowaffle/peloton-to-garmin/releases

**Comment by derekkvedar** [comment]
V3 looks great. I think this issue still has an inconsistency. Basically, peloton uses your 20 Min max power (or manually input value) and then calculates 95% of it to get your FTP. This program seems to be pulling the 20 Minute max power (or manually input value), but not taking the 95% value.

Of note, this has also transitioned to affect any ride (power zone, etc), not only Just Rides. So now all peloton-converted TSS and IF values will be inaccurate.

Objective for this function would be to look back at a previous FTP value for when a ride was taken (ie for converting a ride taken on Aug 20, 2021, look up the FTP value at that time). I dont think peloton stores this data, but I know Garmin keeps historics. This is much less important than getting the 95% area corrected though.

**Comment by philosowaffle** [comment]
>  This program seems to be pulling the 20 Minute max power (or manually input value), but not taking the 95% value.

Well, this appears to be a case of Peloton incorrectly labeling their data... checkout what they have named the [data field](https://github.com/philosowaffle/peloton-to-garmin/blob/master/UnitTests/Data/cycling_just_ride.json#L5) that P2G uses. They are inaccurately reporting this value as the FTP when in fact it seems to be the max 20min Avg Power.

In fact, even on normal classes where the workout [includes the FTP information](https://github.com/philosowaffle/peloton-to-garmin/blob/master/UnitTests/Data/cycling_workout.json#L231), they advertise this as the FTP.

For context my avg max 20m output is 154w making my FTP is 146.

So I'm not sure what their deal is with mis-representing this data, but that's the core of the issue. I can obviously fix this, but as far as I can tell, its always been this way.  P2G has always taken the Peloton reported FTP at face value.

I've created #287 to add the needed calculation.

**Comment by derekkvedar** [comment]
Yeah, sounds like a case of a mis-labeled variable.

Interesting context - my old FTP test (in the screenshot above) was 323 (correctly converted from P2G), because the 20min average was 341w. That was for an update based on an FTP test, not an update from manually punching in the number. I wonder if it saves differently in the Peloton variable if you update from a peloton ride, versus manually updating your FTP in the peloton settings.

**Comment by philosowaffle** [comment]
Well, sounds like I"m gonna have to put myself through the pain of an FTP test to see if I can figure out the Peloton magic sauce.  I've only ever manually set the value, haven't tried updating direct from a test ride.  Perhaps this will be tmrws workout 🤔 

(unless you happen to have the generated JSON from that MattWilpers ride?)

**Comment by derekkvedar** [comment]
if you can talk me through how to pull the JSON from any of my rides, i'm happy to do that for you
